name: monkey_lib
description: A new Flutter project.
 
publish_to: 'none'  
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ansicolor:
  async:
  meta:
  stream_channel:
  uuid:
  web_socket_channel:
  photo_manager:
  permission_handler:
  rxdart:
  shimmer:
  photo_view:
  device_preview: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
